"use client";

/* Signature that writes itself across the hero as the page scrolls.
 *
 * Sits over the OWIE wordmark, like the references. The word is outlines from
 * a script face, generated by tools/make-signature.py, so no font is fetched
 * at runtime.
 *
 * The reveal is a mask, not a wipe: one thick stroke runs the length of the
 * word along the writing line, and its dash offset follows scroll position, so
 * the letters uncover in writing order and unwrite on the way back up.
 * Animating the letterforms' own dash offset instead would trace around each
 * outline, up one side of a stroke and back down the other, which reads as
 * circling the letters rather than writing them.
 *
 * mix-blend-mode: difference gives it no colour of its own: white over the
 * dark hero, inverted wherever it crosses the mark beneath.
 *
 * To try another face, change the import below. tools/make-signature.py writes
 * app/signature-{alexbrush,stylescript,zeyada,nothingyoucoulddo}.json.
 */

import { useEffect, useId, useRef } from "react";
import data from "./signature-alexbrush.json";

const EASE = 0.1;
const clamp01 = (v: number) => Math.min(1, Math.max(0, v));

export default function Signature({ className }: { className?: string }) {
  const id = useId().replace(/:/g, "");
  const maskId = `sig-${id}`;
  const wrap = useRef<HTMLDivElement>(null);
  const pen = useRef<SVGPathElement>(null);

  useEffect(() => {
    const box = wrap.current;
    const stroke = pen.current;
    if (!box || !stroke) return;

    const length = stroke.getTotalLength();
    stroke.style.strokeDasharray = `${length}`;

    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      stroke.style.strokeDashoffset = "0";
      return;
    }

    let frame = 0;
    let current = 0;
    let target = 0;

    const measure = () => {
      const r = box.getBoundingClientRect();
      const vh = window.innerHeight || 1;
      // Writes across the first two thirds of a viewport of scrolling.
      target = clamp01((vh - r.top) / (vh * 0.66));
    };

    const paint = (t: number) => {
      stroke.style.strokeDashoffset = `${length * (1 - t)}`;
    };

    const tick = () => {
      current += (target - current) * EASE;
      const done = Math.abs(target - current) < 0.001;
      if (done) current = target;
      paint(current);
      frame = done ? 0 : requestAnimationFrame(tick);
    };

    const onScroll = () => {
      measure();
      if (!frame) frame = requestAnimationFrame(tick);
    };

    measure();
    current = target;
    paint(current);

    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });

    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      cancelAnimationFrame(frame);
    };
  }, []);

  return (
    <div className={className} ref={wrap} aria-hidden="true">
      <svg viewBox={data.viewBox} role="presentation">
        <defs>
          <mask id={maskId} maskUnits="userSpaceOnUse">
            <path
              ref={pen}
              d={data.pen}
              fill="none"
              stroke="#fff"
              strokeWidth={data.penWidth}
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </mask>
        </defs>
        <g mask={`url(#${maskId})`}>
          {data.paths.map((d, i) => (
            <path key={i} d={d} fill="#fff" />
          ))}
        </g>
      </svg>
    </div>
  );
}
